// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxEMl52AMPzsdktHAfNrMGoCzocRb2UPU',
    appId: '1:161182624335:web:7bf8d00ee4699bb06bd83a',
    messagingSenderId: '161182624335',
    projectId: 'twitterclone-tc123',
    authDomain: 'twitterclone-tc123.firebaseapp.com',
    storageBucket: 'twitterclone-tc123.appspot.com',
    measurementId: 'G-V06BRXM28H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNAJBiVa-BGFcQ0KPLNQ-QSXkOj_Mc1HM',
    appId: '1:161182624335:android:8231a8c80d098f946bd83a',
    messagingSenderId: '161182624335',
    projectId: 'twitterclone-tc123',
    storageBucket: 'twitterclone-tc123.appspot.com',
  );
}
